
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class DestroyByContact : MonoBehaviour
{
    private BossController BossController;
    // Start is called before the first frame update
    void Start()
    {
        //rd2d = GetComponent<Rigidbody2D>();
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    private void OnTriggerEnter(Collider other)
    {
        Destroy(other.gameObject);
        Destroy(gameObject);
    }
    private void OnCollisionEnter2D(Collision2D collision)
    {
        if (collision.collider.tag == "Enemy")
        {
            Destroy(collision.collider.gameObject);
            //collision.gameObject.SetActive(false);
            Destroy(gameObject);
        }

        /*if (collision.collider.tag == "Boss")
        {
            transform.position = new Vector2(-4f, -0.7f);
        }*/
    }
}
